function d(){this.a=window.location;this.b="https:"===this.a.protocol?"wss://"+this.a.host+"/ws/vocabularies":"ws://"+this.a.host+"/ws/vocabularies";this.c=function(){var a=e,b=new WebSocket(this.b);b.onopen=function(){b.send('{"d":0,"c":0,"m":0}')};b.onmessage=function(b){a(b)}};this.f=function(){var a=f.value,b=g,c=h+2,k=l,z=new WebSocket(this.b);z.onopen=function(){z.send('{"d":'+a+',"c":'+b+',"m":'+c+"}")};z.onmessage=function(a){k(a)}};return this}window.Vocabularies=d;/*
 aydos.com */
var m,n,p,q,g,r,h,t,u,v,w,f,x,y,A,B,C,D=new d,E=[];
window.onload=function(){C=document.getElementById("btn");C.disabled=!0;C.onclick=F;w=document.getElementById("err");if(window.WebSocket){w.innerHTML="Loading vocabularies...";f=document.getElementById("voc");x=document.getElementById("cnt");y=document.getElementById("dur");A=document.getElementById("mdur");B=document.getElementById("thm");t=document.getElementById("over");u=document.getElementById("word");v=document.getElementById("mean");u.style.textAlign="center";u.style.font="bold 4rem Arial";
v.style.textAlign="center";v.style.font="bold 2rem Arial";for(var a=10;100>=a;a+=10){var b=document.createElement("option");b.value=a;b.innerHTML=a;x.appendChild(b)}for(a=1;24>=a;a++)b=document.createElement("option"),b.value=a,b.innerHTML=a+" s.",y.appendChild(b);for(a=1;24>=a;a++)b=document.createElement("option"),b.value=a,b.innerHTML=a+" s.",A.appendChild(b);y.value=1;A.value=-1;D.c();window.onkeydown=G;t.onmousedown=H;t.onmouseup=I}else w.innerHTML="Your browser does not support WebSockets."};
function G(a){27==("which"in a?a.which:a.keyCode)&&J()}function H(){n=setTimeout(J,960);0>=q&&K()}function I(){clearTimeout(n)}
function F(){r=+y.value;h=+A.value;g=+x.value;D.f();thm=B.value;u.innerHTML="&nbsp;";v.innerHTML="&nbsp;";thm%2?(t.style.backgroundColor="#111",t.style.color="#FAFAFA",u.style.color="#FAFAFA",v.style.color="#FAFAFA"):(t.style.backgroundColor="#FAFAFA",t.style.color="#111",u.style.color="#111",v.style.color="#111");v.innerHTML="Loading words...";t.style.display="flex";q=3;p=0}function J(){clearTimeout(m);clearTimeout(n);t.style.display="none"}
function L(){u.innerHTML=q;v.innerHTML="'esc' or 'long tap' to exit...";q?(q--,m=setTimeout(L,1E3)):(v.innerHTML="",clearTimeout(m),K())}function K(){var a=Math.floor(p/2);p==2*g?J():(0!=thm&&1!=thm&&(2==thm?(u.style.color=M(1),v.style.color=M(1)):3==thm&&(u.style.color=M(2),v.style.color=M(2))),u.innerHTML=E[a].w,-2==h?(p+=2,a=r):-1==h?(v.innerHTML=E[a].m,p+=2,a=r):p%2?(v.innerHTML=E[a].m,p++,a=h):(v.innerHTML="&nbsp;",p++,a=r),0<a&&(m=setTimeout(K,1E3*a)))}
function e(a){a=JSON.parse(a.data);for(var b="",c=0;c<a.length;c++){var k=document.createElement("option");k.value=a[c].i;k.innerHTML=a[c].s+" "+a[c].t+" &mdash; "+a[c].d;b+="<li>"+a[c].d+" ("+a[c].s+" &mdash; "+a[c].t+", "+a[c].w+" words)</li>";f.appendChild(k)}w.innerHTML="";C.disabled=!1;document.getElementById("vocinfo").innerHTML=b}function l(a){E=JSON.parse(a.data);L()}function N(a,b){return Math.floor(Math.random()*(b-a+1)+a)}
function M(a){for(var b="#",c=0;3>c;c++)b=0==a?b+"0123456789ABCDEF"[N(0,15)]:1==a?b+"0123456789ABCDEF"[N(0,7)]:b+"0123456789ABCDEF"[N(8,15)],b+="0123456789ABCDEF"[N(0,15)];return b};
