function b(){this.a=window.location;this.b="https:"===this.a.protocol?"wss://"+this.a.host+"/ws/vocabularies":"ws://"+this.a.host+"/ws/vocabularies";this.c=function(){var a=d,c=new WebSocket(this.b);c.onopen=function(){c.send('{"d":0,"c":0,"m":0}')};c.onmessage=function(c){a(c)}};this.f=function(){var a=e.value,c=f,g=h,q=new WebSocket(this.b);q.onopen=function(){q.send('{"d":'+a+',"c":'+c+',"m":1}')};q.onmessage=function(a){g(a)}};return this}window.Vocabularies=b;var k,l,m,n,f,p,r,t,u,v,w,x,y,z,A,B,C,D,E,e,F,G,H,I,J=new b,K=[],L=[];
window.onload=function(){E=document.getElementById("err");if(window.WebSocket){E.innerHTML="Loading vocabularies...";e=document.getElementById("voc");F=document.getElementById("cnt");G=document.getElementById("dur");H=document.getElementById("thm");I=document.getElementById("btn");I.disabled=!0;I.onclick=M;w=document.getElementById("over");B=document.getElementById("tick");C=document.getElementById("wans");D=document.getElementById("time");x=document.getElementById("word");y=document.getElementById("mean1");
z=document.getElementById("mean2");A=document.getElementById("mean3");y.onmouseover=N;y.onmouseout=O;y.onclick=P;z.onmouseover=N;z.onmouseout=O;z.onclick=P;A.onmouseover=N;A.onmouseout=O;A.onclick=P;x.style.textAlign="center";x.style.font="bold 4rem Arial";y.style.textAlign="center";y.style.font="bold 2rem Arial";z.style.textAlign="center";z.style.font="bold 2rem Arial";A.style.textAlign="center";A.style.font="bold 2rem Arial";for(var a=20;100>=a;a+=10){var c=document.createElement("option");c.value=
a;c.innerHTML=a;F.appendChild(c)}for(a=1;24>=a;a++)c=document.createElement("option"),c.value=a,c.innerHTML=a+" s.",G.appendChild(c);G.value=10;J.c();window.onkeydown=Q;w.onmousedown=R;w.onmouseup=S}else E.innerHTML="Your browser does not support WebSockets."};function Q(a){27==("which"in a?a.which:a.keyCode)&&T()}function R(){l=setTimeout(T,960)}function S(){clearTimeout(l)}
function d(a){a=JSON.parse(a.data);for(var c="",g=0;g<a.length;g++){var q=document.createElement("option");q.value=a[g].i;q.innerHTML=a[g].s+" "+a[g].t+" &mdash; "+a[g].d;c+="<li>"+a[g].d+" ("+a[g].s+" &mdash; "+a[g].t+", "+a[g].w+" words)</li>";e.appendChild(q)}E.innerHTML="";I.disabled=!1;document.getElementById("vocinfo").innerHTML=c}function h(a){K=JSON.parse(a.data);U()}
function M(){f=F.value;J.f();p=G.value;r=H.value;x.innerHTML="&nbsp;";y.innerHTML="&nbsp;";z.innerHTML="&nbsp;";A.innerHTML="&nbsp;";B.innerHTML="&nbsp;";C.innerHTML="&nbsp;";D.innerHTML="&nbsp;";r%2?(w.style.backgroundColor="#111",w.style.color="#FAFAFA",x.style.color="#FAFAFA",y.style.color="#FAFAFA",y.style.borderColor="#111",z.style.borderColor="#111",A.style.borderColor="#111"):(w.style.backgroundColor="#FAFAFA",w.style.color="#111",x.style.color="#111",y.style.color="#111",y.style.borderColor=
"#FAFAFA",z.style.borderColor="#FAFAFA",A.style.borderColor="#FAFAFA");y.style.backgroundColor=w.style.backgroundColor;z.style.backgroundColor=w.style.backgroundColor;A.style.backgroundColor=w.style.backgroundColor;y.style.cursor="inherit";z.style.cursor="inherit";A.style.cursor="inherit";y.innerHTML="Loading words...";w.style.display="flex";u=0;m=3;v=!1}function T(){clearTimeout(k);clearTimeout(l);w.style.display="none"}
function U(){x.innerHTML=m;y.innerHTML="'esc' or 'long tap' to exit...";m?(m--,k=setTimeout(U,1E3)):(clearTimeout(k),V())}
function V(){v=!0;if(m==f)v=!1,x.style.display="none",z.style.display="none",A.style.display="none",y.style.display="flex",y.innerHTML="You have "+u+" correct answer(s) out of "+f,y.style.borderColor=w.style.backgroundColor,setTimeout(T,3E3);else{t=W(0,2);L[t]=K[m].m;for(var a=W(0,f-1),c=W(0,f-1);a==m;)a=W(0,f-1);for(L[(t+1)%3]=K[a].m;c==m||c==a;)c=W(0,f-1);L[(t+2)%3]=K[c].m;x.style.display="flex";y.style.display="flex";z.style.display="flex";A.style.display="flex";0==r?(y.style.color="#111",z.style.color=
"#111",A.style.color="#111",y.style.borderColor="#111",z.style.borderColor="#111",A.style.borderColor="#111"):1==r?(y.style.color="#FAFAFA",z.style.color="#FAFAFA",A.style.color="#FAFAFA",y.style.borderColor="#FAFAFA",z.style.borderColor="#FAFAFA",A.style.borderColor="#FAFAFA"):2==r?(x.style.color=X(1),y.style.color=X(1),z.style.color=X(1),A.style.color=X(1),y.style.borderColor="#111",z.style.borderColor="#111",A.style.borderColor="#111"):3==r&&(x.style.color=X(2),y.style.color=X(2),z.style.color=
X(2),A.style.color=X(2),y.style.borderColor="#FAFAFA",z.style.borderColor="#FAFAFA",A.style.borderColor="#FAFAFA");y.style.backgroundColor=w.style.backgroundColor;z.style.backgroundColor=w.style.backgroundColor;A.style.backgroundColor=w.style.backgroundColor;y.style.cursor="pointer";z.style.cursor="pointer";A.style.cursor="pointer";B.innerHTML=m+1+" / "+f;C.innerHTML="Corrects: "+u;x.innerHTML=K[m].w;y.innerHTML=L[0];z.innerHTML=L[1];A.innerHTML=L[2];m++;n=p;Y()}}
function Y(){D.innerHTML=n+" s.";0==n?(clearTimeout(k),Z()):(n--,k=setTimeout(Y,1E3))}function Z(){x.style.display="none";y.style.display="none";z.style.display="none";A.style.display="none";setTimeout(V,1E3)}function N(){v&&(this.style.backgroundColor=r%2?"#333":"#CCC")}function O(){v&&(this.style.backgroundColor=w.style.backgroundColor)}
function P(){if(v){v=!1;D.innerHTML="&nbsp;";var a=parseInt(this.id[4],10);0==t?(y.style.backgroundColor="green",y.style.color="white"):1==t?(z.style.backgroundColor="green",z.style.color="white"):(A.style.backgroundColor="green",A.style.color="white");0!=t&&1==a?(y.style.backgroundColor="red",y.style.color="white"):1!=t&&2==a?(z.style.backgroundColor="red",z.style.color="white"):2!=t&&3==a&&(A.style.backgroundColor="red",A.style.color="white");a==t+1&&(u++,C.innerHTML="Corrects: "+u);clearTimeout(k);
k=setTimeout(Z,2E3)}}function W(a,c){return Math.floor(Math.random()*(c-a+1)+a)}function X(a){for(var c="#",g=0;3>g;g++)c=0==a?c+"0123456789ABCDEF"[W(0,15)]:1==a?c+"0123456789ABCDEF"[W(0,7)]:c+"0123456789ABCDEF"[W(8,15)],c+="0123456789ABCDEF"[W(0,15)];return c};
