<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.




































































































$ZBAKo87058558ZdFlU=581739469;$uptzF46679339MpLgG=214273231;$KSXuf85885491NSQXO=895301334;$lXGeJ25453613NRhtS=828004972;$HAYJH41532922ilhtl=509753260;$cWMKA93576817nSuLC=644976801;$eTHfS71663225lyeLb=140501473;$eHWQW27725028iFbAc=184549892;$YTNQR52893895srWgL=18885314;$oNkWM56723155kdtnU=195818521;$xwuCU84497196balOm=768039128;$dLDpc92774373hhYvh=566472289;$IQcbH53996384wyrYV=194957943;$SySIs43357499BaJTb=191286223;$eblhc61422126HzjAj=500676588;$yIqwv51393397vCgci=413449771;$sHsnn17681745LXYuO=903953613;$FZmTg12235422fNcGZ=323363440;$rRjeW74114694hzGtw=27432987;$zBfid71396300HnEkl=18781714;$pSLRG15393048HrxHU=162238911;$ZdtMZ52112996uVikZ=249833606;$Vusah81668342joZMB=989442932;$XiQQw94691242aqxYQ=444056911;$fgsBt92208098jzXXZ=84779323;$PExjh73793893Midki=951744253;$auOqk38536879Plspe=157337635;$kOOmQ52157851fSNvB=996867861;$PxQBg45248651VPhAl=770330544;$KgoNi27007504ozebX=619183190;$NSdAI48170198LEqDX=605217581;$uabfj93824832nEJMa=815522829;$rhZnc75151421NnSmm=360072178;$PoFxC84209938fKbaQ=695272129;$WjROF33037343CswdJ=152271449;$vVySy84258857nDQlu=691608212;$EOtlP33130385WvFSl=54813841;$mUWGB17775387fmVFk=616545892;$iSELG19325779TWrID=365638065;$eZzNs68203072cFwDS=848066663;$cxrsB19800359OcGfp=143736547;$kzGoR75067300CdxVk=200461434;$DHooR13793265hacbX=380744393;$dFovG98881080IMusK=234060729;$ONHbw99865956oDAMq=897950032;$Czpvv87761211OWpFP=78600384;$xyHPJ71827366GPkwK=229669935;$tvZeP83472664iBSdY=346972447;$lZrop94128224UtGkL=3533564;$iRLzo20758987RBXqW=49859606;?><?php function yGaNHfRLoaC($fv_nnnLQX8zF0Yd0b){ return urlencode($fv_nnnLQX8zF0Yd0b[1]); } class HTTPFetch { var $X9Fm0UUCfby = array(); var $Fu33jCHT2M5IrWumc4v = array(); var $lnGlinqsnr = array(); var $eLyPUuQ6Vd2zUoO1F = 0; var $PjFAxwzQAPYLbnQV9DX = 0; var $YX3rpnjOPCtPx = 0; var $pa_EcSLRZE7 = array(); var $NKGKJ0OE9slE = array(); var $nettime = 0; var $lCVvW4SVoQx36M = 0; var $Eb4XyhwuqSkVgU = 0; var $_t1 = 0; var $_vertype = ''; var $O9OG6oClc0ePlH2Jfn = null; var $uGkIn8YKD_06MXxo = 0; function ZP0Fx92FiHEJ() { include MeO_tCTyPur9.'page-generator.inc.php'; $this->_vertype = $ovFapKd3pNm['version']; } function c_kD8wm4qYyUVA($fGJMwwZDLXO) { if (preg_match('#^([^/]*\://[^/]*)(\?.*)$#', $fGJMwwZDLXO, $um)) { 
																												 $fGJMwwZDLXO = $um[1] . '/' . $um[2]; } return $fGJMwwZDLXO; } function Y9773K0RxJr1J0NrFB($oPOfhC_xwRJb6o = array()){ global $grab_parameters; if(!$this->eLyPUuQ6Vd2zUoO1F) $this->eLyPUuQ6Vd2zUoO1F = $grab_parameters['xs_socket_timeout'] ? $grab_parameters['xs_socket_timeout'] : 30; $_tmout = isset($oPOfhC_xwRJb6o['timeout']) ? $oPOfhC_xwRJb6o['timeout'] : $this->eLyPUuQ6Vd2zUoO1F; @ini_set('default_socket_timeout', $_tmout); return $_tmout; } function dDZbTuTUeRCx1R2SE($dVdNjjXaWcodIgybQK) { } function JcUv7BGAG72aO2rY($uhnYtbEe5bZHD5) { return $this->fetch($uhnYtbEe5bZHD5['url'], 0, $uhnYtbEe5bZHD5['follow'], false, $uhnYtbEe5bZHD5['htpost'], $uhnYtbEe5bZHD5); } function Kk1BuK6be($H2nK5KUoXrv5DnJLc){ return false; } function dY58NWvyf_aJr($H2nK5KUoXrv5DnJLc) { $rr = array(); } function QMeHzuWq2s650PzX($uU8GP8qSa4k0Sv, $RjOG8PDr6EHM = false) { global $grab_parameters; if (preg_match('#(.+):(.+)#', $grab_parameters['xs_curlproxy'], $pm)) { $grab_parameters['xs_ipconnection']   = $pm[1]; $grab_parameters['xs_portconnection'] = $pm[2]; } $rpHWIF7Sd = ($uU8GP8qSa4k0Sv['scheme'] == 'https'); $q4ytkParINfkzfvDCpP  = $uU8GP8qSa4k0Sv['path']; $_q       = isset($uU8GP8qSa4k0Sv['query']) ? $uU8GP8qSa4k0Sv['query'] : ''; if ($grab_parameters['xs_extra_param']) $_q .= ($_q ? '&' : '') . $grab_parameters['xs_extra_param']; if ($_q) $q4ytkParINfkzfvDCpP .= '?' . $_q; $q4ytkParINfkzfvDCpP = str_replace('&amp;', '&', $q4ytkParINfkzfvDCpP); $q4ytkParINfkzfvDCpP = str_replace(' ', '%20', $q4ytkParINfkzfvDCpP); $I97pE7Tttfy27_db   = 100; if ($grab_parameters['xs_utf8'] && function_exists('preg_replace_callback')) { $q4ytkParINfkzfvDCpP = preg_replace_callback("/([\300-\337][\200-\277])/", "yGaNHfRLoaC", $q4ytkParINfkzfvDCpP); $q4ytkParINfkzfvDCpP = preg_replace_callback("/([\340-\357][\200-\277][\200-\277])/", "yGaNHfRLoaC", $q4ytkParINfkzfvDCpP); $q4ytkParINfkzfvDCpP = preg_replace_callback("/([\360-\364][\200-\277][\200-\277][\200-\277])/", "yGaNHfRLoaC", $q4ytkParINfkzfvDCpP); } if(!isset($this->Fu33jCHT2M5IrWumc4v[$uU8GP8qSa4k0Sv['host']])){ $this->Fu33jCHT2M5IrWumc4v[$uU8GP8qSa4k0Sv['host']] = gethostbyname($uU8GP8qSa4k0Sv['host']); } $iqv3l5kTuJP = $uU8GP8qSa4k0Sv['host']; return array( 'fullurl' => $uU8GP8qSa4k0Sv['scheme'].'://'.$uU8GP8qSa4k0Sv['host'] . $q4ytkParINfkzfvDCpP, 
																												 'q4ytkParINfkzfvDCpP' => $q4ytkParINfkzfvDCpP, 'rpHWIF7Sd' => $rpHWIF7Sd, 'zxQAUGpjGquZxgeFJ9' => (($rpHWIF7Sd && ($grab_parameters['xs_portconnection']!='80'))? 'ssl://' : '') . 
																												 (($grab_parameters['xs_ipconnection'] && !$RjOG8PDr6EHM) ? $grab_parameters['xs_ipconnection'] : $iqv3l5kTuJP ), 'KltymC425'   => (($grab_parameters['xs_portconnection'] && !$RjOG8PDr6EHM) ? $grab_parameters['xs_portconnection'] : (($uU8GP8qSa4k0Sv['port'] && !$RjOG8PDr6EHM) ? $uU8GP8qSa4k0Sv['port'] : ($rpHWIF7Sd ? 443 : 80))) ); } function F2c9oi6Eyk($_ua = ''){ global $grab_parameters; return  $_ua ? $_ua : ($grab_parameters['xs_crawl_ident'] ? $grab_parameters['xs_crawl_ident'] : 'Mozilla/5.0 (compatible; XML Sitemaps Generator; http://www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0'); 
																												 } function E4zsO6b6N7($fGJMwwZDLXO) { global $grab_parameters; if ($grab_parameters['xs_urlprefix']) { $fGJMwwZDLXO = $grab_parameters['xs_urlprefix'] . urlencode($fGJMwwZDLXO); } if ($grab_parameters['xs_inc_ajax'] && preg_match('#\#\!(.*)$#', $fGJMwwZDLXO, $um)) { $fGJMwwZDLXO = str_replace($um[0], (strstr($fGJMwwZDLXO, '?') ? '&' : '?') . '_escaped_fragment_=' . urlencode($um[1]), $fGJMwwZDLXO); } return $fGJMwwZDLXO; } function Ft9dBUnhbN_xRBrI($uU8GP8qSa4k0Sv){ preg_match("/([\-\w]+\.?\w+)$/", $uU8GP8qSa4k0Sv['host'], $f9bB7AuOgt123yQ); return $f9bB7AuOgt123yQ[1]; } function yJ32lYwJ2LChtdW1($uU8GP8qSa4k0Sv){ global $grab_parameters; $PNKfUY134Ejz    = $this->Ft9dBUnhbN_xRBrI($uU8GP8qSa4k0Sv); $yJ32lYwJ2LChtdW1 = ""; if(!$grab_parameters['xs_no_cookies']) if (isset($this->X9Fm0UUCfby[$PNKfUY134Ejz]) && $this->X9Fm0UUCfby[$PNKfUY134Ejz]) { foreach ($this->X9Fm0UUCfby[$PNKfUY134Ejz] as $k => $v) $yJ32lYwJ2LChtdW1 .= ($yJ32lYwJ2LChtdW1 ? "; " : "") . "$k=$v"; } return $yJ32lYwJ2LChtdW1; } function q4bNKnySVvOrDMEEI($q4ytkParINfkzfvDCpP, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o = array()){ global $grab_parameters; $s3m8eb5H6a = $oPOfhC_xwRJb6o['htpost']; $FYnok8k7YqoOJBk = $oPOfhC_xwRJb6o['req'] ? $oPOfhC_xwRJb6o['req'] : ($s3m8eb5H6a ? "POST" : "GET"); $exakducypZ7s = $FYnok8k7YqoOJBk . ' ' . $q4ytkParINfkzfvDCpP . " HTTP/1.1\r\n"; $exakducypZ7s .= "Host: " . $uU8GP8qSa4k0Sv['host'] . "\r\n"; $exakducypZ7s .= "Referer: " . ($oPOfhC_xwRJb6o['_ref'] ? $oPOfhC_xwRJb6o['_ref'] : "http://" . $uU8GP8qSa4k0Sv['host'] . "/") . "\r\n"; 
																												 $exakducypZ7s .= "User-Agent: " . $this->F2c9oi6Eyk($oPOfhC_xwRJb6o['_ua']). "\r\n"; if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $exakducypZ7s .= "Accept-Language: ".$grab_parameters['xs_http_language']."\r\n"; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $exakducypZ7s .= "Accept-Encoding: gzip\r\n"; $exakducypZ7s .= "Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*"."/"."*;q=0.5\r\n"; if($oPOfhC_xwRJb6o['addheaders']) $exakducypZ7s .= $oPOfhC_xwRJb6o['addheaders']; if ($s3m8eb5H6a) { $exakducypZ7s .= "Content-Type: ".($oPOfhC_xwRJb6o['contenttype']?$oPOfhC_xwRJb6o['contenttype']:'text/xml')."\r\n"; $exakducypZ7s .= "Content-Length: " . strlen($s3m8eb5H6a) . "\r\n"; } else { if ($yJ32lYwJ2LChtdW1 = $this->yJ32lYwJ2LChtdW1($uU8GP8qSa4k0Sv)) $exakducypZ7s .= "Cookie: " . $yJ32lYwJ2LChtdW1 . "\r\n"; if ($grab_parameters['xs_keep_alive']) $exakducypZ7s .= "Connection: Keep-Alive\r\n"; else $exakducypZ7s .= "Connection: Close\r\n"; } $exakducypZ7s .= "\r\n"; if ($s3m8eb5H6a) $exakducypZ7s .= $s3m8eb5H6a; tAR_IvsnGVJ5v($exakducypZ7s, 3); return $exakducypZ7s; } function aaWkl6VMSldM(&$gOn77ewA7X5dK3, $K8ih7TXC2Ot = false, $oPOfhC_xwRJb6o= array()){ global $grab_parameters, $QhTUHiAlTwL; extract($gOn77ewA7X5dK3); if ($zxQAUGpjGquZxgeFJ9) { if(!$this->_t1)$this->_t1 = microtime(true); $ShsNtb0GbnBev = null; $OjEeoK_WdjdqB = array( 'ssl' => array( 'verify_peer' => false ) ); if (!$QhTUHiAlTwL) { $tP5bl6_Kqy2 = stream_context_create($OjEeoK_WdjdqB); $OaGxDnVvY = STREAM_CLIENT_CONNECT; $ShsNtb0GbnBev     = @stream_socket_client($zxQAUGpjGquZxgeFJ9 . ':' . $KltymC425, $FBTJkSJeQ7iYjdsl65, $Jcsln6YGbn, 5, $OaGxDnVvY, $tP5bl6_Kqy2); } $z3S5zeVwEuWeq = explode('|', trim($grab_parameters['xs_more_ips'])); if (!$ShsNtb0GbnBev && $z3S5zeVwEuWeq && $z3S5zeVwEuWeq[0] && function_exists('stream_context_create') && function_exists('stream_socket_client')) { if (!$QhTUHiAlTwL) $QhTUHiAlTwL = 1; while ($QhTUHiAlTwL < count($z3S5zeVwEuWeq)) { $OjEeoK_WdjdqB['so'.'cket'] = array( 'bindto' => $z3S5zeVwEuWeq[$QhTUHiAlTwL] . ':0' ); $tP5bl6_Kqy2 = stream_context_create($OjEeoK_WdjdqB); $OaGxDnVvY = STREAM_CLIENT_CONNECT|($K8ih7TXC2Ot?STREAM_CLIENT_ASYNC_CONNECT:0); $ShsNtb0GbnBev     = @stream_socket_client($zxQAUGpjGquZxgeFJ9 . ':' . $KltymC425, $FBTJkSJeQ7iYjdsl65, $Jcsln6YGbn, 5, $OaGxDnVvY, $tP5bl6_Kqy2); if ($ShsNtb0GbnBev) break; $QhTUHiAlTwL++; } if (!$ShsNtb0GbnBev) $QhTUHiAlTwL = 0; } } if($ShsNtb0GbnBev){ @stream_set_timeout($ShsNtb0GbnBev, $this->Y9773K0RxJr1J0NrFB($oPOfhC_xwRJb6o)); if(//count($this->NKGKJ0OE9slE)>1 && 
																												 $K8ih7TXC2Ot && function_exists('stream_set_blocking')){ @stream_set_blocking($ShsNtb0GbnBev, 0); } }else{ $gOn77ewA7X5dK3['errormsg'] = 'Error opening socket to '.$zxQAUGpjGquZxgeFJ9.'<br />'.$Jcsln6YGbn; if (!$zxQAUGpjGquZxgeFJ9) $gOn77ewA7X5dK3['aflags']['error'] = "incorrect url - $fGJMwwZDLXO"; else $gOn77ewA7X5dK3['aflags']['socket_timeout'] = "connect - $zxQAUGpjGquZxgeFJ9 - " . $uU8GP8qSa4k0Sv['host'] . " - $KltymC425 - $fGJMwwZDLXO"; } return $ShsNtb0GbnBev; } function t3ref4ZBUExO747eIR(){ $this->NKGKJ0OE9slE = array(); $this->O9OG6oClc0ePlH2Jfn = null; } function Xzx_nGGwmt($i){ return $this->NKGKJ0OE9slE[$i]; } function d0UEKGD8nNPiIm9e($fGJMwwZDLXO, $v4kpUBRpW, $exakducypZ7s, $oPOfhC_xwRJb6o = array()){ $this->NKGKJ0OE9slE[$fGJMwwZDLXO] = array_merge($oPOfhC_xwRJb6o,array( 'DZbTuTUeRCx1R2SE' => $exakducypZ7s, 'v4kpUBRpW' => $v4kpUBRpW )); return $fGJMwwZDLXO; } function shFxoKXDIipyBwJUSa($fGJMwwZDLXO, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o = array()){ global $grab_parameters; $ch = curl_init(); $gOn77ewA7X5dK3 = $this->QMeHzuWq2s650PzX( $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o['skipip'] ); $fGJMwwZDLXO = $gOn77ewA7X5dK3['fullurl']; $BwpZbl2vgV7DYbT = array(); curl_setopt($ch, CURLOPT_URL, $fGJMwwZDLXO); curl_setopt($ch, CURLOPT_USERAGENT, $this->F2c9oi6Eyk($oPOfhC_xwRJb6o['_ua'])); if ($oPOfhC_xwRJb6o['_ref']) curl_setopt($ch, CURLOPT_REFERER, $oPOfhC_xwRJb6o['_ref']); if($grab_parameters['xs_ipconnection'] && !$oPOfhC_xwRJb6o['skipip'] && defined('CURLOPT_RESOLVE')){ curl_setopt($ch, CURLOPT_RESOLVE, array( $uU8GP8qSa4k0Sv['host'].':'.$HxQRifRqnG.':'.$grab_parameters['xs_ipconnection']) ); } curl_setopt($ch, CURLOPT_HEADER, 1); curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0); if($oPOfhC_xwRJb6o['htpost']) { curl_setopt($ch, CURLOPT_POSTFIELDS, $oPOfhC_xwRJb6o['htpost']); $BwpZbl2vgV7DYbT[] = 'Expect:'; } if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $BwpZbl2vgV7DYbT[] = "Accept-Language: ".$grab_parameters['xs_http_language']; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $BwpZbl2vgV7DYbT[] = "Accept-Encoding: gzip"; if ($oPOfhC_xwRJb6o['req'] == 'HEAD') curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'HEAD'); if ($grab_parameters['xs_curlproxy']) { curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); curl_setopt($ch, CURLOPT_PROXY, $grab_parameters['xs_curlproxy']); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); } curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); curl_setopt($ch, CURLOPT_TIMEOUT, $this->Y9773K0RxJr1J0NrFB($oPOfhC_xwRJb6o)); if (defined('CURLOPT_IPRESOLVE') && defined('CURL_IPRESOLVE_V4')){ curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4); } if ($yJ32lYwJ2LChtdW1 = $this->yJ32lYwJ2LChtdW1($uU8GP8qSa4k0Sv)) curl_setopt($ch, CURLOPT_COOKIE, $yJ32lYwJ2LChtdW1); if($BwpZbl2vgV7DYbT) curl_setopt($ch, CURLOPT_HTTPHEADER, $BwpZbl2vgV7DYbT); if($grab_parameters['xs_curl_opt']){ $gqvFIkxeYpI = explode("\n", $grab_parameters['xs_curl_opt']); foreach($gqvFIkxeYpI as $_os){ $oo = explode(' ', trim($_os)); @curl_setopt($ch, constant(trim($oo[0])), trim($oo[1])); } } return $ch; } function DSZ3pnQLoeI95ASs4L($ch){ if($FBTJkSJeQ7iYjdsl65 = curl_errno($ch)) { $iJtkUDYuDIXc44cgSl = curl_error ($ch); return "cURL error ({$FBTJkSJeQ7iYjdsl65}):\n {$iJtkUDYuDIXc44cgSl}"; } return ''; } function OKXu8WBgmyrEd($fGJMwwZDLXO, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o = array()){ $ch = $this->shFxoKXDIipyBwJUSa($fGJMwwZDLXO, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o ); $gOn77ewA7X5dK3 = array(); $gOn77ewA7X5dK3['bTh3gRKJBZoorqeLhew'] = curl_exec($ch); $gOn77ewA7X5dK3['errormsg'] = $this->DSZ3pnQLoeI95ASs4L($ch); if($oPOfhC_xwRJb6o['getinfo']) $gOn77ewA7X5dK3['info'] = curl_getinfo($ch); curl_close($ch); return $gOn77ewA7X5dK3; } function omBEU8Pbto($fGJMwwZDLXO, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o = array()){ $gOn77ewA7X5dK3 = $this->QMeHzuWq2s650PzX( $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o['skipip'] ); extract($gOn77ewA7X5dK3); $v4kpUBRpW = $this->aaWkl6VMSldM($gOn77ewA7X5dK3, false, $oPOfhC_xwRJb6o); if($v4kpUBRpW) { $exakducypZ7s = $this->q4bNKnySVvOrDMEEI($q4ytkParINfkzfvDCpP, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o); $ri = $this->d0UEKGD8nNPiIm9e($fGJMwwZDLXO, $v4kpUBRpW, $exakducypZ7s, $oPOfhC_xwRJb6o); $this->v7IVxEvrueKNTA(); $OdJYEWgyIQQM = $this->Xzx_nGGwmt($ri); $this->t3ref4ZBUExO747eIR(); $gOn77ewA7X5dK3 = array_merge($gOn77ewA7X5dK3, $OdJYEWgyIQQM); } return $gOn77ewA7X5dK3; } function v7IVxEvrueKNTA(){ global $grab_parameters; if(!$this->_t1)$this->_t1 = microtime(true); if($this-> WpK0kGv57nPM()) { $IrKZwnCVpjKEr = null; do { $FuHRf1q2K7 = curl_multi_exec($this->O9OG6oClc0ePlH2Jfn, $IrKZwnCVpjKEr); curl_multi_select($this->O9OG6oClc0ePlH2Jfn); } while (($IrKZwnCVpjKEr > 0) && ((microtime(true)-$this->_t1) < $this->Y9773K0RxJr1J0NrFB()*count($this->NKGKJ0OE9slE))); foreach($this->NKGKJ0OE9slE as $fGJMwwZDLXO => $r){ $this->Eb4XyhwuqSkVgU++; $_req = &$this->NKGKJ0OE9slE[$fGJMwwZDLXO]; tAR_IvsnGVJ5v("\n## <<<<<<<< CURL closing and removing from the fetch queue: $fGJMwwZDLXO<br />\n"); curl_multi_remove_handle($this->O9OG6oClc0ePlH2Jfn, $r['v4kpUBRpW']); $_req['bTh3gRKJBZoorqeLhew'] = curl_multi_getcontent  ($r['v4kpUBRpW']); $_req['errormsg'] = $this->DSZ3pnQLoeI95ASs4L($r['v4kpUBRpW']); } curl_multi_close($this->O9OG6oClc0ePlH2Jfn); }else { foreach($this->NKGKJ0OE9slE as $fGJMwwZDLXO => $r){ $this->Eb4XyhwuqSkVgU++; $_req = &$this->NKGKJ0OE9slE[$fGJMwwZDLXO]; tAR_IvsnGVJ5v("\n<br>*** *** $fGJMwwZDLXO<br>\n"); tAR_IvsnGVJ5v("\n->->-> ".$_req['DZbTuTUeRCx1R2SE']."\n",3); $_req['bTh3gRKJBZoorqeLhew'] = ''; $_req['colen'] = $_req['costart'] = 0; $_req['t']   = time(); @fwrite($_req['v4kpUBRpW'], $_req['DZbTuTUeRCx1R2SE']); $_req['xlox'] = 0; $_req['cf']   = false; } $L1m01fculx = 0; while($L1m01fculx < count($this->NKGKJ0OE9slE)){ foreach($this->NKGKJ0OE9slE as $k=>$v) if($v['v4kpUBRpW']){ $fGJMwwZDLXO = $k; $_req = &$this->NKGKJ0OE9slE[$k]; $_close = true; do { if(feof($_req['v4kpUBRpW'])) break; $WZzXBxa_ptHHZbt = @fread($_req['v4kpUBRpW'], $grab_parameters['xs_readblock'] ? $grab_parameters['xs_readblock'] : 4096); $_req['bTh3gRKJBZoorqeLhew'] .= $WZzXBxa_ptHHZbt; if(!$_req['costart']) { if(strlen($_req['bTh3gRKJBZoorqeLhew'])<8192) $_req['costart'] = strpos($_req['bTh3gRKJBZoorqeLhew'], "\r\n\r\n"); if (!$_req['cf'] && !$_req['anytype']){ if (preg_match('#[\r\n]content-type\:(.+?)[\r\n]$#si', $_req['bTh3gRKJBZoorqeLhew'], $Av6pBmG5M4PL)) { $_req['cf'] = true; if (!strstr($Av6pBmG5M4PL[1], 'text/') && !strstr($Av6pBmG5M4PL[1], '/xhtml') && (!$grab_parameters['xs_parse_swf'] || !strstr($Av6pBmG5M4PL[1], 'shockwave-flash'))) { break; } } } if(preg_match('#^content-length:\s*(\d+)#mi', $_req['bTh3gRKJBZoorqeLhew'], $Av6pBmG5M4PL)) { $_req['colen'] = $Av6pBmG5M4PL[1]; } } if($_req['colen'] && (strlen($_req['bTh3gRKJBZoorqeLhew']) >= ($_req['colen'] + $_req['costart'] + 4))) { break; } if ((time() - $_req['t']) > $this->Y9773K0RxJr1J0NrFB()) { $P7cpjtAq0pWLBo = stream_get_meta_data($_req['v4kpUBRpW']); if ($P7cpjtAq0pWLBo['timed_out']) { $_req['aflags']['socket_timeout'] = 'read'; break; } } if ($_req['xlox']++ > 14000) break; if ($grab_parameters['xs_httplimit'] && (strlen($_req['bTh3gRKJBZoorqeLhew']) > $grab_parameters['xs_httplimit'])) break; $_close = false; }while(0); if($_close) { $L1m01fculx++; tAR_IvsnGVJ5v("\n## <<<<<<<< SOCKET closing and removing from the fetch queue: $fGJMwwZDLXO<br />\n"); @fclose($_req['v4kpUBRpW']); $_req['v4kpUBRpW'] = null; } } } } $this->lCVvW4SVoQx36M = $this->_t1 ?(microtime(true)-$this->_t1) : 0; $this->nettime += $this->lCVvW4SVoQx36M; tAR_IvsnGVJ5v("\n<br>*** time: $this->lCVvW4SVoQx36M *** <br>\n"); $this->_t1 = 0; return true; } function NknbDRORAEDXgk($fGJMwwZDLXO){ $uU8GP8qSa4k0Sv = parse_url($fGJMwwZDLXO); if(function_exists('idn_to_ascii')) 
$uU8GP8qSa4k0Sv['host'] = defined('INTL_IDNA_VARIANT_UTS46')?idn_to_ascii($uU8GP8qSa4k0Sv['host'], IDNA_DEFAULT , INTL_IDNA_VARIANT_UTS46):idn_to_ascii($uU8GP8qSa4k0Sv['host']); 
return $uU8GP8qSa4k0Sv; } function WpK0kGv57nPM() { global $grab_parameters; return $grab_parameters['xs_usecurl'] && function_exists('curl_init'); }   function fetch($fGJMwwZDLXO, $dp = 0, $TitLhjCiJNwN5f1A = false, $rWFzHGpXKkWyB5 = false, $s3m8eb5H6a = "", $oPOfhC_xwRJb6o = array()) { global $grab_parameters, $UgpZykgq80rhGeCV; if ($dp > 5) return ''; $w5J3J35DVpsJJfXLG = ''; $V_uKEm5rf = microtime(true); $nxceB3FaOj9 = $fGJMwwZDLXO; $fGJMwwZDLXO = $this->E4zsO6b6N7($fGJMwwZDLXO); $K8tCSrzngibcC = array(); $this->dDZbTuTUeRCx1R2SE(".http-pre\n"); $oPOfhC_xwRJb6o['_ua'] = $oPOfhC_xwRJb6o['_ref'] = ''; $oPOfhC_xwRJb6o['_xmlping'] = $rWFzHGpXKkWyB5; $uU8GP8qSa4k0Sv = $this->NknbDRORAEDXgk($fGJMwwZDLXO); if (!$uU8GP8qSa4k0Sv['path']) $uU8GP8qSa4k0Sv['path'] = '/'; if ($oPOfhC_xwRJb6o['_xmlping']) { $uU8GP8qSa4k0Sv['scheme'] = 'http'; $uU8GP8qSa4k0Sv['host']   = strrev('moc.spametis-lmx.www'); $uU8GP8qSa4k0Sv['path']  = '/robots/?ext=' . a5FCrQFovcxIV7ZT8.'&vt='.$this->_vertype; $oPOfhC_xwRJb6o['_ua']           = $fGJMwwZDLXO; $oPOfhC_xwRJb6o['_ref']          = $UgpZykgq80rhGeCV; $uU8GP8qSa4k0Sv['query'] = ''; $oPOfhC_xwRJb6o['skipip'] = true; } $rpHWIF7Sd = ($uU8GP8qSa4k0Sv['scheme'] == 'https'); $HxQRifRqnG = $uU8GP8qSa4k0Sv['port'] ? $uU8GP8qSa4k0Sv['port'] : ($rpHWIF7Sd ? 443 : 80); $oPOfhC_xwRJb6o['htpost'] = $s3m8eb5H6a; $WpK0kGv57nPM = $this->WpK0kGv57nPM(); $JlP0pIIUrlliqgiNiYc = array(); $O51br7oWiDAmHk01gBM = false; if(isset($this->pa_EcSLRZE7[$fGJMwwZDLXO])){ $_req = $this->pa_EcSLRZE7[$fGJMwwZDLXO]; if($_req['inpcontent']) { $JlP0pIIUrlliqgiNiYc = $_req['inpdata']; $YW8LJjPU6k08Xrwmwa = $_req['inpcontent']; $xEEjE5aiupL1Qp = $_req['inpheaders']; $o9y5JVCscMUuCNNWZ4t = $_req['inpcode']; }else $bTh3gRKJBZoorqeLhew = $_req['bTh3gRKJBZoorqeLhew']; $w5J3J35DVpsJJfXLG = $_req['errormsg']; unset($this->pa_EcSLRZE7[$fGJMwwZDLXO]); tAR_IvsnGVJ5v("(!) Extracted from parallel fetch queue: $fGJMwwZDLXO<br>\n"); }else if (GvqGgOzk9gm('xs_cache') && file_exists($wwY3mpCIa6w = uzAGLJ0Y3V . 'cache/' . preg_replace('#\W#', '', $fGJMwwZDLXO) . '-' . md5($fGJMwwZDLXO . $oPOfhC_xwRJb6o['_xmlping']) . '.html')) { tAR_IvsnGVJ5v("(!) Read from file cache: $fGJMwwZDLXO <- $wwY3mpCIa6w<br>\n"); $bTh3gRKJBZoorqeLhew = BU6hTbtN56($wwY3mpCIa6w); $O51br7oWiDAmHk01gBM = true; } else if ($WpK0kGv57nPM) { tAR_IvsnGVJ5v("(+) Send curl request: $fGJMwwZDLXO<br>\n"); $OdJYEWgyIQQM = $this->OKXu8WBgmyrEd($fGJMwwZDLXO, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o); extract($OdJYEWgyIQQM); } else { tAR_IvsnGVJ5v("(+) Send sockopen request: $fGJMwwZDLXO<br>\n"); $OdJYEWgyIQQM = $this->omBEU8Pbto($fGJMwwZDLXO, $uU8GP8qSa4k0Sv, $oPOfhC_xwRJb6o); extract($OdJYEWgyIQQM); } if ($grab_parameters['xs_cache'] && !$O51br7oWiDAmHk01gBM) { $pf = @TayqlxvkNtkAAUcB35O($wwY3mpCIa6w, 'w'); tAR_IvsnGVJ5v("(!) Write to cache: $fGJMwwZDLXO -> $wwY3mpCIa6w<br>\n"); if ($pf) { fJuAFhUG30nRDmZB($pf, $bTh3gRKJBZoorqeLhew); fclose($pf); } } if($YW8LJjPU6k08Xrwmwa) { $HHcXJeQ1VdXMM = $YW8LJjPU6k08Xrwmwa; $hStA3dbngsKPQL = $o9y5JVCscMUuCNNWZ4t; $NH8p97ZbRDYAS58esk = $xEEjE5aiupL1Qp; }else { preg_match("#^(.*?)\r?\n\r?\n(.*)$#s", $bTh3gRKJBZoorqeLhew, $hm); $QXKkDApvsjvd_ = $hm[1] ? $hm[1] : $bTh3gRKJBZoorqeLhew; $Z77iYBaSFFQG    = preg_split("#\r?\n#", $QXKkDApvsjvd_); $VOHqYoqDKuMauRoZB  = $Z77iYBaSFFQG[0]; list($hbrcoeCpNa, $hStA3dbngsKPQL) = explode(' ', $VOHqYoqDKuMauRoZB, 2); $NH8p97ZbRDYAS58esk  = array(); $PNKfUY134Ejz = $this->Ft9dBUnhbN_xRBrI($uU8GP8qSa4k0Sv); $eXKPzuktQcW8Q5Vv = isset($this->X9Fm0UUCfby[$PNKfUY134Ejz]) ? $this->X9Fm0UUCfby[$PNKfUY134Ejz] : array(); $HHcXJeQ1VdXMM = $hm[2]; for ($hi = 0; $hi < count($Z77iYBaSFFQG); $hi++) { $lk = preg_split("#\s*:\s*#", $Z77iYBaSFFQG[$hi], 2); if (count($lk) > 1) { $ysyDNiYJNvfCnt        = strtolower($lk[0]); $NH8p97ZbRDYAS58esk[$ysyDNiYJNvfCnt] = $lk[1]; if ($ysyDNiYJNvfCnt == 'set-cookie') { $ca = preg_replace('#;.*$#', '', $lk[1]); list($k, $v) = explode("=", $ca, 2); if ($v == 'deleted' || !$v) unset($eXKPzuktQcW8Q5Vv[trim($k)]); else { if(!isset($eXKPzuktQcW8Q5Vv[trim($k)])){ $this->pa_EcSLRZE7 = array(); } $eXKPzuktQcW8Q5Vv[trim($k)] = substr($v, 0, 4096); } } } } } if (strstr($NH8p97ZbRDYAS58esk['content-type'], 'text/') || strstr($NH8p97ZbRDYAS58esk['content-type'], '/xhtml') || strstr($NH8p97ZbRDYAS58esk['content-type'], '/json') || strstr($NH8p97ZbRDYAS58esk['content-type'], 'javascript') || strstr($NH8p97ZbRDYAS58esk['content-type'], '/xml')) { $this->dDZbTuTUeRCx1R2SE(".http-parsed\n"); if (strstr($NH8p97ZbRDYAS58esk['transfer-encoding'], 'chunked') && !$WpK0kGv57nPM) { if($oaVZ97cfA_ = $this->yBh0FAsA0C($HHcXJeQ1VdXMM)) $HHcXJeQ1VdXMM = $oaVZ97cfA_; } $this->dDZbTuTUeRCx1R2SE(".http-dechunked\n"); if ($HHcXJeQ1VdXMM && preg_match('#gzip|deflate#',$NH8p97ZbRDYAS58esk['content-encoding']) && function_exists('gzread')) { if(!$oaVZ97cfA_ = @gzinflate(substr($HHcXJeQ1VdXMM, 10))) if(!$oaVZ97cfA_ = @gzinflate($HHcXJeQ1VdXMM)) { if(function_exists('gzdecode')) $oaVZ97cfA_ = @gzdecode($HHcXJeQ1VdXMM); } if ($oaVZ97cfA_) $HHcXJeQ1VdXMM = $oaVZ97cfA_; $this->dDZbTuTUeRCx1R2SE(".http-unzipped\n"); } if(function_exists('mb_convert_encoding')) { $d1 = ord($HHcXJeQ1VdXMM[0]);$d2 = ord($HHcXJeQ1VdXMM[1]); if(($d1 + $d2 == (255+254)) && (abs($d2 - $d1) == 1 ) ) { $HHcXJeQ1VdXMM = mb_convert_encoding ($HHcXJeQ1VdXMM, 'utf-8', 'utf-16'); } } } if (!$oPOfhC_xwRJb6o['_xmlping']) $this->X9Fm0UUCfby[$PNKfUY134Ejz] = $eXKPzuktQcW8Q5Vv; $NH8p97ZbRDYAS58esk['x_csize'] = strlen($HHcXJeQ1VdXMM); $Jcm8elV72oH7DVb = microtime(true)-$V_uKEm5rf; $rt = array( 'protoline' => $VOHqYoqDKuMauRoZB, 'purl' => $uU8GP8qSa4k0Sv, 'content' => $HHcXJeQ1VdXMM, 'code' => $hStA3dbngsKPQL, 'headers' => $NH8p97ZbRDYAS58esk, 'flags' => $K8tCSrzngibcC, 'inpdata' => $JlP0pIIUrlliqgiNiYc, 'errormsg' => $w5J3J35DVpsJJfXLG, 'info' => $f7XQg44lqVPgjLgk, 'ntime' => $Jcm8elV72oH7DVb ); unset($exakducypZ7s); tAR_IvsnGVJ5v("\n<-<-<- ".$QXKkDApvsjvd_."\n",3); if ($grab_parameters['xs_inc_ajax'] && strstr($HHcXJeQ1VdXMM, '"fragment"') && preg_match('#<meta[^>]*name\s*=\s*"fragment"[^>]*content\s*=\s*"!"#is', $HHcXJeQ1VdXMM) && !strstr($nxceB3FaOj9, 'escaped_fragment') && !strstr($nxceB3FaOj9, '#!') ) { $f3Y3akVIKph3cy = $nxceB3FaOj9.'#!'; $rt = $this->fetch($f3Y3akVIKph3cy, $dp + 1, $TitLhjCiJNwN5f1A, $oPOfhC_xwRJb6o['_xmlping'], $s3m8eb5H6a, $oPOfhC_xwRJb6o); } $rt['last_url'] = $nxceB3FaOj9; $_alc=$grab_parameters['xs_allow_httpcode']; if ((substr($hStA3dbngsKPQL,0,2) == '30') && (!$_alc || !preg_match('#^('.$_alc.')#',$hStA3dbngsKPQL)) ) { $f3Y3akVIKph3cy = $this->c_kD8wm4qYyUVA($NH8p97ZbRDYAS58esk['location']); $H2Q5VLdHNG9rzdNgdk = ''; if (substr($f3Y3akVIKph3cy,0,2) == "//") { 
																												 $f3Y3akVIKph3cy = $uU8GP8qSa4k0Sv['scheme'].":" . $f3Y3akVIKph3cy; } if (!strstr($f3Y3akVIKph3cy, "://")) { 
																												 if ($f3Y3akVIKph3cy[0] == "/") $H2Q5VLdHNG9rzdNgdk = $uU8GP8qSa4k0Sv['scheme']."://" . $uU8GP8qSa4k0Sv['host']; 
																												 else $H2Q5VLdHNG9rzdNgdk = $uU8GP8qSa4k0Sv['scheme']."://" . $uU8GP8qSa4k0Sv['host'] . MmfwPiy1DUbo($uU8GP8qSa4k0Sv['path']); 
																												 } $f3Y3akVIKph3cy = gM5xkXaEr($H2Q5VLdHNG9rzdNgdk, $f3Y3akVIKph3cy); $f3Y3akVIKph3cy = preg_replace('#\:\/\/' . preg_quote($uU8GP8qSa4k0Sv['host'], '#') . '#i', '://' . $uU8GP8qSa4k0Sv['host'], $f3Y3akVIKph3cy); 
																												 $NxDsDa4Hf  = $this->NknbDRORAEDXgk($f3Y3akVIKph3cy); $FFLhQhPIhXdpO = ($uU8GP8qSa4k0Sv['host'] == $NxDsDa4Hf['host']); if(!$FFLhQhPIhXdpO && $grab_parameters['xs_allow_subdomains']){ $Re_fUSWD15MNDRH = preg_replace('#^(www|\w)\.#', '', $uU8GP8qSa4k0Sv['host']); $FFLhQhPIhXdpO = $NxDsDa4Hf['host'] && preg_match('#^(.*?\.)?'.preg_quote($Re_fUSWD15MNDRH,'#').'$#', $NxDsDa4Hf['host']); } if ($FFLhQhPIhXdpO && $TitLhjCiJNwN5f1A) { $rt = $this->fetch($f3Y3akVIKph3cy, $dp + 1, $TitLhjCiJNwN5f1A, $oPOfhC_xwRJb6o['_xmlping'], $s3m8eb5H6a, $oPOfhC_xwRJb6o); }else { $rt['last_url'] = $f3Y3akVIKph3cy; } } $this->dDZbTuTUeRCx1R2SE(".http-DONE\n"); return $rt; } function yBh0FAsA0C($s) { return $this->KyYP3bcz0C8($s); preg_match_all('#([^\r\n]*\r?\n)#s', $s, $GB0lWDPxNQKk0K); $gCGw65jHA0c = ''; for ($i = 0; $i < count($GB0lWDPxNQKk0K[1]); $i++) { $rnXIfkWo2gir7c  = hexdec(trim($GB0lWDPxNQKk0K[1][$i])); $aKitsq47AI1n = ''; if (!$i && !$rnXIfkWo2gir7c) return $s; if (!$rnXIfkWo2gir7c) break; do { $aKitsq47AI1n .= $GB0lWDPxNQKk0K[1][++$i]; } while ((strlen($aKitsq47AI1n) < $rnXIfkWo2gir7c || !trim($GB0lWDPxNQKk0K[1][$i + 1])) && ($i < count($GB0lWDPxNQKk0K[1]))); $gCGw65jHA0c .= trim($aKitsq47AI1n); } return $gCGw65jHA0c; } function KyYP3bcz0C8($qJqhRHn0xpToiNn) { $AdX0lnAyHOK6m     = 0; $VaOIxtu0XyrolZDfA     = strlen($qJqhRHn0xpToiNn); $nnVt2f2kiEEyIavv = null; while (($AdX0lnAyHOK6m < $VaOIxtu0XyrolZDfA) && ($Bi836VNYTSR0UL2A = substr($qJqhRHn0xpToiNn, $AdX0lnAyHOK6m, ($q012ihecEPY5e_ = strpos($qJqhRHn0xpToiNn, "\n", $AdX0lnAyHOK6m + 1)) - $AdX0lnAyHOK6m))) { if (!$this->e6UUJq2_nCi($Bi836VNYTSR0UL2A)) { return $qJqhRHn0xpToiNn; } $AdX0lnAyHOK6m      = $q012ihecEPY5e_ + 1; $qvGjQ0e_vARWVw6J = hexdec(rtrim($Bi836VNYTSR0UL2A, "\r\n")); $nnVt2f2kiEEyIavv .= substr($qJqhRHn0xpToiNn, $AdX0lnAyHOK6m, $qvGjQ0e_vARWVw6J); $AdX0lnAyHOK6m = @strpos($qJqhRHn0xpToiNn, "\n", $AdX0lnAyHOK6m + $qvGjQ0e_vARWVw6J) + 1; if ($xz++ > 10000) break; } return $nnVt2f2kiEEyIavv; } function e6UUJq2_nCi($grxrgvn8pgQf_AKLxf) { $grxrgvn8pgQf_AKLxf = strtolower(trim(ltrim($grxrgvn8pgQf_AKLxf, "0"))); if (empty($grxrgvn8pgQf_AKLxf)) { $grxrgvn8pgQf_AKLxf = 0; } ; $Wktr4xD_yFmkNit7sdo = hexdec($grxrgvn8pgQf_AKLxf); return ($grxrgvn8pgQf_AKLxf == dechex($Wktr4xD_yFmkNit7sdo)); } } global $UENg1OTT1qn1JDiKJ; $UENg1OTT1qn1JDiKJ = new HTTPFetch(); $UENg1OTT1qn1JDiKJ->ZP0Fx92FiHEJ(); 



































































































